development:
  dialect: "sqlite3"
  database: /home/angeldm/mod/echoview/echoview_development.sqlite

test:
  dialect: "sqlite3"
  database: /home/angeldm/mod/echoview/echoview_test.sqlite

production:
  dialect: "sqlite3"
  database: /home/angeldm/mod/echoview/echoview_production.sqlite
